### PR TITLE
Upgrade aws-sdk to v3

### PR DESCRIPTION
**Pull request by samnang**
We faced an issue when I upgraded one of our rails apps to 5.2 to use ActiveStorage with amazon s3 which it requires aws-sdk v3.

This PR is inspired by #75 which already closed for some reasons, so I decided to re-submit it.

### CODE REVIEW

**Comment by yeonhoyoon** [comment]
If rails 5.2's new credentials are used, you also need to configure secret_key_base as per this comment: https://github.com/tawan/active-elastic-job/issues/87#issuecomment-385799242

**Comment by yeonhoyoon** [comment]
Thanks @samnang for this PR.

If rails 5.2's new credentials are used, you also need to configure secret_key_base as per this comment: https://github.com/tawan/active-elastic-job/issues/87#issuecomment-385799242

**Comment by llenodo** [comment]
@tawan any plans to merge this PR? Has this project been abandoned?

**Comment by rubyisbeautiful** [comment]
This is great! I'm using in a staging application, about to move to production, since the ActiveStorage component is not that critical.
 I forked and tried to get the specs to pass.  Even after supplying the missing AWS_REGION, it fails on missing AWS credentials.  I'm not sure how @tawan had them working originally.  
If we all had more time I see value in separating the real AWS calls into some feature specs, and stubbing AWS calls in unit specs.  For now we would all like to see AWS SDK v3 get rolled into master.  Do you have any advice, anything we can do to help move this along @tawan?

**Comment by kceb** [comment]
Bump. Just started a new project with activestorage and would love to use active-elastic-job

**Comment by MartinVandersteen** [comment]
Same, need this :+1:

**Comment by YoranBrondsema** [comment]
Same here, any way we can get this PR merged?

**Comment by YoranBrondsema** [comment]
I was having this issue too but I see that it's already using v3 in the `master` branch (per [this commit](https://github.com/tawan/active-elastic-job/commit/79444e75bd7ac2377bffffdd76feac8e614c795d)). It just hasn't been released yet.

@tawan Any chance you can release a new version? The latest release is from February 2017 and looking at the list of commits, there have been quite a few improvements since then.

**Comment by seanarnold** [comment]
@tawan  any updates please?

**Comment by paulleader** [comment]
@YoranBrondsema 

> I was having this issue too but I see that it's already using v3 in the `master` branch (per [this commit](https://github.com/tawan/active-elastic-job/commit/79444e75bd7ac2377bffffdd76feac8e614c795d)). It just hasn't been released yet.

Have you been using master? Is it working ok?

**Comment by rubyisbeautiful** [comment]
In production, I've been using @samnang ['samnang:upgrade_to_aws_sdk_3'](https://github.com/tawan/active-elastic-job/pull/88) and not `master` and the only difference is that in the former, he requires `aws-sdk-sqs` in `lib/active_elastic_job.rb` which I think is needed in order to not have to require it yourself.  That's why in both branches, it is required in `spec/helpers.rb`.

**Comment by YoranBrondsema** [comment]
@paulleader We were using the master branch and it was working well. However, since we stopped deploying to Elastic Beanstalk, we're not actively using this gem anymore.

**Comment by Mubramaj** [comment]
Forked @samnang and using it on production. Would love to see this merged.

**Pull request merged**
