### PR TITLE
Document aws_region configuration setting

### PR DESCRIPTION
**Pull request by YoranBrondsema**

### CODE REVIEW

**Comment by joeyparis** [comment]
It looks like I need additional access to merge the V3 branch (with fixed Travis testing) into this PR and #97. Can you allow me to do that, or merge branch V3 in yourself? Thank you.

**Comment by YoranBrondsema** [comment]
@joeyparis I gave you write access to https://github.com/sutori/active-elastic-job. Is that what you meant?

**Comment by joeyparis** [comment]
I'm still getting this error when attempting to merge V3 into your PR (only seems to be happening to you and the author of #111). But with write access, I should be able to accomplish what I need. Thank you!
Screen Shot 2020-12-22 at 4 45 21 PM

**Comment by YoranBrondsema** [comment]
@joeyparis I rebased `V3` into this branch and the one from https://github.com/tawan/active-elastic-job/pull/97. Does that achieve what you wanted to do?

**Comment by joeyparis** [comment]
@YoranBrondsema looks like it! Travis CI has been going extra slow, but the queued tests look correct. Hopefully they'll all complete by tomorrow. Thanks for your help!

**Comment by YoranBrondsema** [comment]
No worries! Always happy to see an open-source project being maintained.

**Comment by joeyparis** [comment]
We've been using this for almost 3 years now, least we can do is try to keep it up-to-date for all of us! Definitely going to be a learning experience for me maintaining a widely used project like this but I'm still excited

**Pull request merged**
