### PR TITLE
Add rails 7.2 support, add more matrix testing to github actions

### PR DESCRIPTION
**Pull request by ssunday**
- Added ruby 3.2/3.3 to matrix testing, along with Rails 7.1 + 7.2 (_think_ targets are correct)
- Used `try` to handle when `secrets` is not there 
- Updated checkout action

Want to test installing this on a project with Rails 7.2 to verify it launches in a fully rails env, hence draft status

### CODE REVIEW

**Comment by ssunday** [comment]
Do we want to drop Rails 5.2+ 6 and ruby 2.7 support from this release?

**Comment by samsonjs** [comment]
I'm in favour of dropping the old versions since we don't have many people maintaining this gem.

**Comment by ssunday** [comment]
@samsonjs With that being said (maintenance), I've just learned that https://github.com/aws/aws-sdk-rails actually supports the ElasticBeanstalk worker environment flow for active job—maybe we should deprecate gem in favor of pointing people to use that, which is maintained by AWS? I haven't tried aws-sdk-rails out to see if it's a seamless switch. I'll try it out on a project soon™.

**Comment by januszm** [comment]
@ssunday oh! this is an enlightenment! I haven't looked at this package before. As one of the current maintainers of this gem I actually switched to using the worker tier with the [Shoryuken](https://github.com/ruby-shoryuken/shoryuken) task queue (uses SQS/SNS as a queue store/broker).
Please let me know how aws-sdk-rails works for you, I may switch to it too. And I also think that this gem will be deprecated soon. I'm in touch with AWS support an we already discussed few changes they may add to their EB roadmap regarding using the Worker tier in more "traditional" way (no POST endpoints needed, just the SQS ActiveJob queue adapters)

**Comment by samsonjs** [comment]
Thanks @ssunday that's news to me too! I'm using this in production with millions of requests per day so I'll look into aws-sdk-rails.

**Comment by ssunday** [comment]
@samsonjs @januszm Cool! I'll report back when I get to trying it out on one of my projects. That gem has SO many features—I knew it had active job, but I didn't see the Elastic Beanstalk worker integration until now LOL.

**Comment by januszm** [comment]
@ssunday it's relatively new https://github.com/aws/aws-sdk-rails/tree/main/lib/active_job/queue_adapters
added 3 months ago, before that this gem or Shoryuken were the best solutions

**Comment by samsonjs** [comment]
They renamed it at that time but it seems to have been around since 2020 so it should be in great shape: https://github.com/aws/aws-sdk-rails/pull/42

**Comment by ssunday** [comment]
It looks like it's having issues with dockerized elastic beanstalk apps (I'm guessing the same underlying problem as https://github.com/active-elastic-job/active-elastic-job/pull/154)—returning 403 all the time. I'll raise an issue and maybe get a fix out. 

I replaced a non-docker EB app that was using shoryuken with it and it works fine.

**Comment by ssunday** [comment]
https://github.com/aws/aws-sdk-rails/issues/154 adding it here

**Comment by ssunday** [comment]
Apparently that wasn't the issue, it seems to be an IP thing. Anyway, I'm going to close this PR and open an issue to discuss like...updating docs to point to the other gem in any case.

**Comment by samsonjs** [comment]
I've migrated my staging and production environments away from active-elastic-job and over to aws-activejob-sqs. We set up an ElasticBeanstalk web environment and then use a custom Procfile to run the workers alongside our web server (so health checks are successful, the web servers in this EB env don't serve web requests). Everything went off without a hitch. I created a new queue for a seamless transition.

Huge thanks to active-elastic-job and everyone who created it and maintains it! It was a core piece of infrastructure for about 7 years 🫡

**Comment by januszm** [comment]
@samsonjs  just curious, could you share your solution for custom Procfiles? I tried 2 approaches, either generating them during deployment dynamically or using one procfile that launches custom shell scripts that either run a regular webserver and no workers or run a tiny health-check-only web server with  actual workers

**Comment by samsonjs** [comment]
@januszm Yes this is the contents of my Procfile:

```
web: bundle exec puma -C config/puma_elasticbeanstalk.rb
worker: script/worker-entrypoint
```

You may not need this level of complexity, but we also process S3 event notifications on a second queue, and we deploy this to 2 EB web environments one which actually handles web traffic, and then a second one that only processes queue jobs. This is the contents of script/worker-entrypoint: (which must be executable with `chmod +x script/worker-entrypoint`)

```shell
#!/bin/bash

set -euo pipefail

if [[ "${PROCESS_SQS_JOBS:-}" = "on" ]]; then
  # Run both of these in the background.
  bundle exec aws_active_job_sqs --queue default --threads "${WORKER_THREADS:-$(nproc)}" &
  bundle exec bin/rails s3_events:process &

  # Wait for any background job to finish, so that when one dies the whole process dies and
  # the Elastic Beanstalk engine will restart it.
  wait -n
  jobs
  echo "One of the queue workers exited, hopefully EB restarts us"
else
  echo "SQS worker disabled in this environment – idling forever"
  # Keep the process alive so EB thinks everything is fine.
  while true; do
    sleep 86400
  done
fi
```

**Comment by samsonjs** [comment]
If you don't need all of that then a simple Procfile like this might work for you:

```
web: bundle exec puma -C /opt/elasticbeanstalk/private/pumaconf.rb
worker: bundle exec aws_active_job_sqs --queue default
```

**Comment by ssunday** [comment]
You don't even need a Procfille if you want to do it the typical EB way https://github.com/aws/aws-sdk-rails?tab=readme-ov-file#elastic-beanstalk-activejob-processing

**Comment by samsonjs** [comment]
Also what @ssunday said! If you're happier with the EB worker environment then you don't need to do what I did

**Comment by januszm** [comment]
Thanks for sharing this, so if I remember correctly, the EB Worker tier still requires the web application server to run and respond to health checks. Back in time, I wanted to optimize resources usage (lower memory consumption and Instance type/size) and this is the trick I used on the Worker:

Procfile
```
web: bin/web
worker: bin/worker
```

where `bin/web` is
```sh
#!/usr/bin/env ruby
require "fileutils"

APP_ROOT = File.expand_path("..", __dir__)

FileUtils.chdir APP_ROOT do
  # Replace Rails server with a no-op tiny webserver to satisfy EB worker tier requirement
  if ENV["WORKER"].to_i == 1
    system "bundle exec ruby worker_http.rb"
  else
    system "bundle exec puma -C /opt/elasticbeanstalk/config/private/pumaconf.rb --pidfile /var/app/current/tmp/pids/server.pid"
  end
end
```

instead of the main app, it just runs a tiny Sinatra app that only responds to health checks. I was able to lower the memory usage with this significantly.  On the Worker tier I just set the WORKER=1 env var. `bin/worker` just lunches the worker on the Worker tier, and is ignored on Web tier.

**Comment by samsonjs** [comment]
Smart way to optimize things!

**Pull request closed without merging**
